add fetch
dawidzon/Blogzadanie-II pull request #1
Opened 2022-11-20 11:29 UTC by dawidzon

Testowy pull request.

Dodałem dane poprzez fetch.

https://user-images.githubusercontent.com/53623545/202899423-93a4d8f5-3a07-44e9-b211-e12384e957d0.mov

2022-11-21 07:53 UTC, wozny1989 requested changes
@dawidzon One thing 💪

2022-11-21 07:53 UTC, wozny1989 commented on main.js
> +  };
It's completely fine! 🚀 But for challange, try move this function to `async`/`await` approach
```suggestion
  addPostsFromOutside.onclick = async () => {
    const result = await fetch("https://jsonplaceholder.typicode.com/posts?userId=1");
    // ToDo...
  };
```

2022-11-22 14:52 UTC, wozny1989 requested changes

2022-11-22 14:52 UTC, wozny1989 commented on main.js
> +      );
Nope, use [google search ](https://www.google.com/search?q=fetch+async+await&rlz=1C5CHFA_enPL1028PL1028&oq=fetch+async+await&aqs=chrome.0.0i512l8j0i390l2.2726j0j1&sourceid=chrome&ie=UTF-8) if don't know what's I mean :)

2022-11-22 14:54 UTC, wozny1989 commented
@dawidzon By the way, use english description as well. You wouldn't want your future client to see this in this form 😄

2022-11-24 01:00 UTC, dawidzon commented
@wozny1989  - thank you for the hint.

when it comes to async / await, if it's still not OK, then I don't know how to use it xD

2022-11-24 16:15 UTC, wozny1989 requested changes

2022-11-24 16:15 UTC, wozny1989 commented on main.js
> +    });
```suggestion
    data.forEach((article) => {
      articles.push({
        id: articles.length + 1,
        title: article.title,
        body: article.body,
        likesCount: 0,
      });
      render();
    });
```

or more fancy

```suggestion
    data.forEach(({ title, body }) => {
      articles.push({
        id: articles.length + 1,
        title,
        body,
        likesCount: 0,
      });
      render();
    });
```

2022-11-26 07:19 UTC, dawidzon commented
I worked on another branch with login page and forgot to pull version when I change back to fetch branch, becouse of that in this version I add some changes connected with login page.

2022-11-26 11:28 UTC, wozny1989 approved these changes
Perfect 👌

2022-11-26 11:28 UTC, merged

2022-11-26 11:29 UTC, wozny1989 commented
@dawidzon Merged, please switch locally to the `main` branch and pull the latest changes